#!/usr/bin/env bash
# Version bump script for sqlalchemy-jdbcapi

set -e  # Exit on error

BUMP_TYPE="${1}"

if [ -z "$BUMP_TYPE" ]; then
    echo "❌ Error: Bump type required"
    echo "Usage: ./bump-version.sh <major|minor|patch>"
    echo ""
    echo "Examples:"
    echo "  ./bump-version.sh major  # 2.0.0 -> 3.0.0"
    echo "  ./bump-version.sh minor  # 2.0.0 -> 2.1.0"
    echo "  ./bump-version.sh patch  # 2.0.0 -> 2.0.1"
    exit 1
fi

if [[ ! "$BUMP_TYPE" =~ ^(major|minor|patch)$ ]]; then
    echo "❌ Error: Invalid bump type: $BUMP_TYPE"
    echo "Must be one of: major, minor, patch"
    exit 1
fi

# Get current version from git tags
CURRENT_VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')

if [ -z "$CURRENT_VERSION" ]; then
    echo "❌ Error: No git tags found"
    echo "Please create an initial tag first:"
    echo "  git tag v2.0.0"
    exit 1
fi

echo "📊 Current version: ${CURRENT_VERSION}"

# Parse version
IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

# Bump version
case $BUMP_TYPE in
    major)
        MAJOR=$((MAJOR + 1))
        MINOR=0
        PATCH=0
        ;;
    minor)
        MINOR=$((MINOR + 1))
        PATCH=0
        ;;
    patch)
        PATCH=$((PATCH + 1))
        ;;
esac

NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"

echo "📈 New version: ${NEW_VERSION}"
echo ""

# Update version in _version.py
echo "📝 Updating src/sqlalchemy_jdbcapi/_version.py..."
cat > src/sqlalchemy_jdbcapi/_version.py << EOF
# This file is automatically generated by setuptools_scm
# Do not edit this file manually

__version__ = version = "${NEW_VERSION}"
__version_tuple__ = version_tuple = (${MAJOR}, ${MINOR}, ${PATCH})
EOF

# Update CHANGELOG.md
echo "📝 Updating CHANGELOG.md..."
TODAY=$(date +%Y-%m-%d)
sed -i "s/## \[2\.0\.0\] - 2025-XX-XX/## [${NEW_VERSION}] - ${TODAY}/" CHANGELOG.md

# Show changes
echo ""
echo "✅ Version bumped to ${NEW_VERSION}"
echo ""
echo "Changes made:"
echo "  - src/sqlalchemy_jdbcapi/_version.py"
echo "  - CHANGELOG.md (if applicable)"
echo ""
echo "Next steps:"
echo "  1. Review changes: git diff"
echo "  2. Commit: git add -A && git commit -m 'chore: Bump version to ${NEW_VERSION}'"
echo "  3. Tag: git tag v${NEW_VERSION}"
echo "  4. Push: git push && git push --tags"
echo "  5. Release: ./release.sh ${NEW_VERSION}"
